
" ========== Vundle ========================

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'Yggdroot/indentLine'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdcommenter'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'nvie/vim-flake8'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'kchmck/vim-coffee-script'
Plugin 'altercation/vim-colors-solarized'
Plugin 'MarcWeber/vim-addon-local-vimrc'
Plugin 'derekwyatt/vim-scala'
Plugin 'w0rp/ale'

call vundle#end()
filetype plugin indent on


" ========== General ========================

set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set hidden
set lazyredraw			            "Don't update while executing macros
set showmode
set wildmenu
set ignorecase			            "Case insensitive search
set smartcase			              "Except when the search has casing
set encoding=utf-8  		        "The encoding displayed.
set fileencoding=utf-8  	      "The encoding written to file.
set hlsearch                    "Highlight search matches
set ttyfast                     "Better redraw performance
set re=1                        "Use the old regex engine


" ========== Extra Settings =================

source ~/.vim/mappings.vim	    "Keyboard mappings
source ~/.vim/plugins.vim	      "Plugin-specific settings


" ========== Look & Feel ====================

syntax enable
set background=dark
colorscheme solarized

set term=xterm-256color
set termencoding=utf-8

" Font settings
if has('gui_running')
  if has("gui_macvim")
    set guifont=Monaco:h15
  elseif has("win32")
    set guifont=Consolas\ 15
  else
    set guifont=Ubuntu\ Mono\ 15
  endif
endif


" ========== Indentation ====================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab


" ========== Misc ==========================
au CursorHold,CursorHoldI * checktime   "Trigger file change check
