
" ========== Vundle ========================

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()            " required
filetype plugin indent on    " required


" ========== General ========================

set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set hidden
set lazyredraw			"Don't update while executing macros
set showmode
set wildmenu
set ignorecase			"Case insensitive search
set smartcase			"Except when the search has casing
set encoding=utf-8  		"The encoding displayed.
set fileencoding=utf-8  	"The encoding written to file.

" ========== Font ==========================

source ~/.vim/mappings.vim	"Keyboard mappings
source ~/.vim/plugins.vim	"Plugin-specific settings


" ========== Look & Feel ====================

filetype plugin indent on
syntax enable
set background=dark
if has('gui_running')
  set background=dark
  colorscheme solarized
  " Font settings
  if has("gui_macvim")
    set guifont=Consolas\ 18
  elseif has("win32")
    set guifont=Consolas\ 18
  else
    set guifont=Ubuntu\ Mono\ 14
  endif

else
  colorscheme torte
endif


" ========== Indentation ====================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
