
" ========== Vundle ========================

set nocompatible
filetype off

call plug#begin()

Plug 'w0rp/ale'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Yggdroot/indentLine'
Plug 'scrooloose/nerdcommenter'
Plug 'preservim/nerdtree'
Plug 'jparise/vim-graphql'
Plug 'hashivim/vim-terraform'
"Plug 'pangloss/vim-javascript'
"Plug 'mxw/vim-jsx'
"Plug 'leafgarland/typescript-vim'

" Initialize plugin system
call plug#end()

filetype plugin indent on


" ========== General ========================

set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set hidden
set lazyredraw			            "Don't update while executing macros
set showmode
set wildmenu
set ignorecase			            "Case insensitive search
set smartcase			              "Except when the search has casing
set encoding=utf-8  		        "The encoding displayed.
set fileencoding=utf-8  	      "The encoding written to file.
set hlsearch                    "Highlight search matches
set ttyfast                     "Better redraw performance
set foldmethod=syntax           "Syntax based folding
set foldlevel=999

let g:loaded_matchparen=1


" ========== Extra Settings =================

source ~/.vim/mappings.vim	    "Keyboard mappings
source ~/.vim/plugins/ale.vim
source ~/.vim/plugins/ctrlp.vim
source ~/.vim/plugins/coc.vim
source ~/.vim/plugins/nerdtree.vim
source ~/.vim/plugins/netrw.vim
source ~/.vim/plugins/misc.vim


" ========== Look & Feel ====================

syntax on
set background=dark
colorscheme habamax

set term=xterm-256color
set termencoding=utf-8

" Font settings
if has('gui_running')
  if has("gui_macvim")
    set guifont=Menlo:h15
  elseif has("win32")
    set guifont=Consolas\ 15
  else
    set guifont=Ubuntu\ Mono\ 15
  endif
endif


" ========== Indentation ====================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab


" ========== Project Configuration ==========

set exrc      " evaluate project configuration files


" ========== Misc ===========================

highlight badwhitespace ctermbg=red guibg=darkred
au CursorHold,CursorHoldI * checktime   "Trigger file change check

set secure  " disable unsafe commands from custom .vimrc
